### ISSUE TITLE
Error: Unable to compile TypeScript:

### ISSUE THREAD

**Issue by NitinKanawalli** [ssehmi/e2e#1]
getting this below error:

Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1574317448.886][WARNING]: FromSockAddr failed on netmask
[1574317448.886][WARNING]: FromSockAddr failed on netmask
[0-0] RUNNING in chrome - /src/features/homepage-search.feature
[0-0] Error: ⨯ Unable to compile TypeScript:
src/stepDefinitions/homepage-search.steps.ts(4,55): error TS2339: Property 'decorate' does not exist on type 'typeof Reflect'.
src/stepDefinitions/homepage-search.steps.ts(4,92): error TS2339: Property 'decorate' does not exist on type 'typeof Reflect'.
src/stepDefinitions/homepage-search.steps.ts(32,111): error TS2322: Type '0' is not assignable to type '{ label: number; sent: () => any; trys: any[]; ops: any[]; }'.
src/stepDefinitions/homepage-search.steps.ts(83,5): error TS2539: Cannot assign to 'HomepageSearchSteps' because it is not a variable.

[0-0] FAILED in chrome - /src/features/homepage-search.feature

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:03

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! e2e@1.0.0 test: `wdio`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the e2e@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nitinkanawalli/.npm/_logs/2019-11-21T06_24_12_696Z-debug.log

**Comment by ssehmi** [comment]
Strange for some reason typescript cannot find reflect on your env... I have added this as a dev dependency and to the tsconfig, can you pull and try again

**Comment by ssehmi** [comment]
Closing as cannot replicate, and fix put in place
